### PR TITLE
Script to anonymize test data

### PR DESCRIPTION
**Pull request by colwem**
Here you go SP.  Hopefully this works. let me know if there's a problem.  I forgot to write down exactly what we discussed so I tried to do this from memory.  It just replaces every name with "p#" where # is an index.  It then randomly shuffles ratings. 

My test data:
input:
```
[
  {
    "name": "john",
    "rating": "1111",
    "friends": "carl rebeca"
  },
  {
    "name": "carl",
    "rating": "2222",
    "friends": "rebeca"
  },
  {
    "name": "rebeca",
    "rating": "3333",
    "friends": "buncha bull"
  }
]
```
output:
```
[
    {
        "name": "p0",
        "rating": "3333",
        "friends": "p1 p2"
    },
    {
        "name": "p1",
        "rating": "2222",
        "friends": "p2"
    },
    {
        "name": "p2",
        "rating": "1111",
        "friends": "buncha bull"
    }
]
```

### CODE REVIEW

**Comment by michael1241** [comment]
A few things:
Should the gitignore be included? I thought those always stay local. Or at least that makes sense to me since not everyone will have the same things.
The pattern matching for friends/avoids doesn't work quite right - some are replaced and some are not. I'm not sure if it's because you're using a different re (I used [^-_a-zA-Z0-9]+ to split)? 
Also it looks like you're generating the replacenames again for each name in the list? I guess it should be the same order so no result change but seems odd. Unless I'm misunderstanding.

**Comment by colwem** [comment]
> Should the gitignore be included? I thought those always stay local. Or at least that makes sense to me since not everyone will have the same things.

A .gitignore should always be committed to your project.  This is standard practice.  You put things to ignore that are exclusive to you in `.git/info/exclude`  I have a file that I copy there every time I check out a repo which covers my editor's backup files and other random stuff my particular workflow creates.  However the .gitignore should cover everything that shouldn't be committed which the project itself tends to generate.  Things like `*.py[cod]` and `__pycache__/`.

> The pattern matching for friends/avoids doesn't work quite right - some are replaced and some are not. I'm not sure if it's because you're using a different re (I used [^-_a-zA-Z0-9]+ to split)?

I forgot about avoid so are all the missing names just from avoid or also in friends?  I'm not sure why it wouldn't be working otherwise.  I'm not splitting, I'm just replacing in place.  Do you notice any kind of pattern to what is missed?  I will add the avoid field and update the pull request shortly.

> Also it looks like you're generating the replacenames again for each name in the list? I guess it should be the same order so no result change but seems odd. Unless I'm misunderstanding.

Yes, it was in the wrong place but it makes no difference.  Just less efficient.

**Comment by colwem** [comment]
Ugg forget it, that won't work either, I'll just rewrite this this weekend.

**Comment by colwem** [comment]
Ok, now it should work.  Hopefully, maybe, ???

**Pull request merged**
